version: '3.1'

services:

  nginx:
    container_name: sf4-rest-nginx
    build:
      context: .docker/config/nginx
    ports:
      - 8000:80
    working_dir: /application
    volumes:
      - .:/application
      - .docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: sf4-rest-php
    build:
      context: .docker/config/php
    ports:
      - 9000:9000
    working_dir: /application
    volumes:
      - .:/application
      - .docker/config/php/php.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

  mysql:
    container_name: sf4-rest-mysql
    build:
      context: .docker/config/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=symfony
    working_dir: /application
    volumes:
      - .:/application

  memcached:
    container_name: sf4-rest-memcached
    build:
      context: .docker/config/memcached
    ports:
      - 11211:11211

  redis:
    container_name: sf4-rest-redis
    build:
      context: .docker/config/redis
    ports:
      - 6379:6379
